# Tasker Configuration File
database:
  host: "manager.broadbandcatalysts.com"
  port: 5432
  dbname: "geodb"
  user: "warnes"
  password: "%6932wbEpwxt"
  
# Optional settings
logging:
  console: true
  level: "INFO"
